Fix parsing of module version
In the Debian autobuilders, the build fails with the following `UnicodeDecodeError` using Python 3.5:
```
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 38: ordinal not in range(128)
```
Most likely, this is due to the copyright sign added as a result of the copyright header normalization.

The following patch fixes the problem.